services:
  - type: web
    name: mi-app-django
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,*.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"
      - key: DB_NAME
        value: "proyecto_875j"
      - key: DB_USER
        value: "joseph202503"
      - key: DB_PASSWORD
        value: "FHUzCivZxEiwkuS98gRBSU24MNp9tYhf"
      - key: DB_HOST
        value: "dpg-d6v8e41r0fns73c4l24g-a"
      - key: DB_PORT
        value: "5432"
    startCommand: python render_start.py
