services:
  - type: web
    name: mi-app-django
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: SECRET_KEY
        generateValue: true
    buildCommand: docker build -f Dockerfile -t app .
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 --workers 4 SGIEVpy.wsgi:application
