# Generated by Django 5.2.7 on 2025-11-12 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=60)),
                ('descripcion_categoria', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensajeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mensajeria', models.CharField(max_length=45)),
                ('tel_mensajeria', models.CharField(max_length=20)),
                ('direccion_mensajeria', models.CharField(max_length=100)),
                ('cobertura', models.CharField(max_length=45)),
                ('activo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('correo_proveedor', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20)),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('contacto_telefono', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_identificacion', models.BigIntegerField()),
                ('tipo_usu', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=10)),
                ('p_nombre', models.CharField(max_length=15)),
                ('s_nombre', models.CharField(max_length=15)),
                ('p_apellido', models.CharField(max_length=15)),
                ('s_apellido', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=70)),
                ('telefono', models.BigIntegerField()),
                ('salario', models.BigIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion_producto', models.TextField()),
                ('codigo_barras', models.CharField(max_length=50)),
                ('registrosaniario', models.CharField(max_length=100)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margen_ganancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('stock_maximo', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.SmallIntegerField()),
                ('categoria_idcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.categoria')),
                ('proveedor_idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Compra_proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('numero_factura_compra', models.CharField(max_length=10)),
                ('subtotal_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_compra', models.CharField(choices=[('pendiente', 'pendiente'), ('recibida', 'recibida'), ('cancelada', 'Cancelada')], max_length=20)),
                ('observaciones_compra', models.TextField()),
                ('imagen_factura_compra', models.CharField(max_length=255)),
                ('producto_idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.producto')),
                ('usuarios_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Compra_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_compra_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_linea_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lote', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('compra_idcompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.compra_proveedor')),
                ('producto_idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento_inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('venta', 'Venta'), ('compra', 'Compra')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_id', models.IntegerField()),
                ('tipo_referencia', models.CharField(choices=[('venta', 'Venta'), ('compra', 'compra'), ('ajuste', 'Ajuste')], max_length=20)),
                ('observaciones', models.TextField()),
                ('imagen_comprobante', models.CharField(max_length=250)),
                ('producto_idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.producto')),
                ('usuarios_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateTimeField(auto_now_add=True)),
                ('numero_factura', models.CharField(max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('parcial', 'Parcial')], default='pagado', max_length=20)),
                ('observaciones', models.TextField()),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], default='efectivo', max_length=20)),
                ('imagen_recibo', models.CharField(max_length=255)),
                ('usuarios_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_envio', models.CharField(max_length=15)),
                ('fecha_envio', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('direccion_envio', models.CharField(max_length=100)),
                ('direccion_salida', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('novedades', models.TextField()),
                ('fk_mensajeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.mensajeria')),
                ('usuarios_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.usuarios')),
                ('venta_idfactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Venta_has_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.producto')),
                ('venta_idfactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sgiev.venta')),
            ],
        ),
    ]
