# Generated by Django 5.2.8 on 2025-11-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sgiev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='clave',
            field=models.CharField(max_length=128),
        ),
    ]
