# Generated by Django 5.2.7 on 2025-11-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sgiev', '0002_alter_usuarios_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_factura',
            field=models.DateField(auto_now_add=True),
        ),
    ]
