# Generated by Django 5.2.7 on 2025-11-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sgiev', '0003_alter_venta_fecha_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_factura',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
