# Generated by Django 5.2.7 on 2025-11-21 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sgiev', '0004_alter_venta_fecha_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra_proveedor',
            name='proveedor_idproveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sgiev.proveedor'),
            preserve_default=False,
        ),
    ]
