# Generated by Django 5.2.7 on 2025-11-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sgiev', '0005_compra_proveedor_proveedor_idproveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra_proveedor',
            name='producto_idproducto',
        ),
    ]
