# Generated by Django 5.2.7 on 2025-11-26 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sgiev', '0006_remove_compra_proveedor_producto_idproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='registrosaniario',
            new_name='registrosanitario',
        ),
    ]
