# Generated by Django 5.2.7 on 2025-11-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sgiev', '0007_rename_registrosaniario_producto_registrosanitario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_producto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_barras', 'SIN_LOTE_CATALOGO')), fields=('nombre_producto', 'descripcion_producto'), name='unique_maestro_producto'),
        ),
    ]
