# Generated by Django 5.2.7 on 2025-12-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sgiev', '0009_venta_correo_cliente_venta_direccion_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
