# Generated by Django 5.2.7 on 2025-12-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sgiev', '0010_alter_producto_nombre_producto'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producto',
            name='unique_maestro_producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=100),
        ),
    ]
